### ISSUE TITLE
csv broken?

### ISSUE THREAD

**Issue by chrischris292** [BitcoinExchangeFH/BitcoinExchangeFH#127]
Christophers-iMac:BitcoinExchangeFH christopherchan$ bitcoinexchangefh -csv -csvpath data/ -instmts subscriptions.ini
Traceback (most recent call last):
  File "/usr/local/bin/bitcoinexchangefh", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/befh/bitcoinexchangefh.py", line 131, in main
    ExchangeGateway.init_snapshot_table(db_clients)
  File "/usr/local/lib/python3.6/site-packages/befh/exchange.py", line 73, in init_snapshot_table
    [0,1], is_ifnotexists=True)
TypeError: create() got multiple values for argument is_ifnotexists

Christophers-iMac:BitcoinExchangeFH christopherchan$ ls data
Christophers-iMac:BitcoinExchangeFH christopherchan$

**Comment by choandrew** [comment]
I have the same problem

**Comment by choandrew** [comment]
I have the same problem (running on Ubuntu server 16):
ubuntu@XXXXX:~/foldername$ bitcoinexchangefh -csv -csvpath data/ -instmts subscriptions.ini
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/bitcoinexchangefh", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.5/site-packages/befh/bitcoinexchangefh.py", line 131, in main
    ExchangeGateway.init_snapshot_table(db_clients)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/befh/exchange.py", line 73, in init_snapshot_table
    [0,1], is_ifnotexists=True)
TypeError: create() got multiple values for argument 'is_ifnotexists'

The SQLite call seems to work perfectly fine though.

**Comment by asifbahrainwala** [comment]
Hi,
I have the same problem, 
called:
bitcoinexchangefh -csv -csvpath /home/asif/Desktop/ -instmts /home/asif/Desktop/Aurora/BitcoinExchangeFH/subscriptions.ini 

fixed it my end, but then I get 
2018-08-09 13:00:17,985 - ERROR 
[ExchGwGatecoin]
Error in order book: 'module' object has no attribute 'Request'


2018-08-09 13:00:17,990 - ERROR 
[ExchGwPoloniex]
Error in order book: 'module' object has no attribute 'Request'


2018-08-09 13:00:17,991 - ERROR 
[ExchGwPoloniex]
Error in trades: 'module' object has no attribute 'Request'


2018-08-09 13:00:17,992 - ERROR 
[ExchGwBittrex]
Error in order book: 'module' object has no attribute 'Request'


2018-08-09 13:00:17,996 - ERROR 
[ExchGwWex]
Error in order book: 'module' object has no attribute 'Request'


2018-08-09 13:00:17,996 - ERROR 
[ExchGwWex]
Error in trades: 'module' object has no attribute 'Request'

**Comment by gavincyi** [comment]
Resolved in 2019.1.1
