### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by cbearden11** [BitcoinExchangeFH/BitcoinExchangeFH#137]
Getting this error on the new version that uses ccxt, using Windows 10, with mysql.
I'm pulling data from Binance.
On a duplicate install under linux (ubuntu), I don't see this error.
I've tried to make sure that python and all dependencies are the same version between the two systems.

2019-01-10 13:57:28,460 INFO Running handler sql
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\Scripts\bitcoinexchangefh.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\befh\cli.py", line 60, in main
    runner.run()
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\befh\core\runner.py", line 57, in run
    process.start()
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input

**Comment by gavincyi** [comment]
It may be due to spawn multiprocessing in windows. Would suggest to use it in Linux environment currently as all my testing done is in Linux. Will investigate it soon.

**Comment by AlgoTrader5** [comment]
any developments to this issue? i'm trying to run this on python>=3.6 on windows and also receiving this message

> It may be due to spawn multiprocessing in windows. Would suggest to use it in Linux environment currently as all my testing done is in Linux. Will investigate it soon.

**Comment by PokerChang** [comment]
Same error here Python 3.8 on Windows 10.
