### ISSUE TITLE
Can not run in Python 3.8 ,multiprocess start failed

### ISSUE THREAD

**Issue by onefistmam** [BitcoinExchangeFH/BitcoinExchangeFH#165]
I am trying to start a process with 3.8v like this:
`
        sqlHandler = self._handlers['sql'] 
        process = mp.Process(target=sqlHandler.run)
        process.start()
        processes.append(process)
`
but it failed with a TypeError. 
`ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread._local' object`

i google for this and tried several ways like move the mp.Queue() out of the class, but it
still doesn't work, i have no idea for this, really need help as a noob, sorry for submit this issue

**Comment by onefistmam** [comment]
`2020-12-11 13:08:24,834 INFO Loading runner
2020-12-11 13:08:24,834 INFO Creating handler sql
2020-12-11 13:08:26,770 INFO Loading handler SqlHandler
2020-12-11 13:08:26,809 INFO Cannot load websocket exchange Binance and fall into REST api exchange
2020-12-11 13:08:27,201 INFO Loading exchange Binance
2020-12-11 13:08:29,565 INFO Start running the feed handler
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cuijiangkun/local/py/mustang/cli.py", line 60, in main
    runner.run()
  File "/Users/cuijiangkun/local/py/mustang/befh/core/runner.py", line 58, in run
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread._local' object
`

**Comment by onefistmam** [comment]
Well . Changed to 3.5
